.TH DVDISASTER 1 "2006-07-06" "0.70" "Schutz f\[:u]r CD/DVD Medien"

.SH NAME
DVDISASTER \- Schutz f\[:u]r CD/DVD Medien gegen Datenverlust durch Alterung
oder Kratzer

.SH SYNTAX
.B dvdisaster
.RB [\| \-r \||\| \-c \||\| \-f \||\| \-s \||\| \-t \||\| \-u \|]
.RB [\| \-d
.IR device \|]
.RB [\| \-p
.IR prefix \|]
.RB [\| \-i
.IR image \|]
.RB [\| \-e
.IR eccfile \|]
.RB [\| \-\-list \|]
.RB [\| \-j
.IR n \|]
.RB [\| -n
.IR n% \|]
.RB [\| -m
.IR n \|]
.RB [\| -v \|]
.RB [\| \-\-adaptive-read \|]
.RB [\| \-\-auto-suffix \|]
.RB [\| \-\-cache-size
.IR n \|]
.RB [\| \-\-dao \|]
.RB [\| \-\-fill-unreadable
.IR n \|]
.RB [\| \-\-query-size
.IR n \|]
.RB [\| \-\-speed-warning
.IR n \|]
.RB [\| \-\-spinup\-dalay
.IR n \|]
.RB [\| \-\-split\-files \|]
.RB [\| \-\-keep-style \|]

.SH BESCHREIBUNG
.B DVDISASTER
erzeugt einen Sicherheitspuffer gegen Datenverluste, die auf CD- und
DVD-Datentr\[:a]gern durch Alterung oder Kratzer entstehen. Es erzeugt
Fehlerkorrekturdaten, um bei nachfolgenden Datentr\[:a]ger-Problemen unlesbare
Sektoren zu rekonstruieren.

.SH TYPISCHE ANWENDUNGEN

.TP
\fBdvdisaster\fP \fB-d\fP \fI/dev/hdc\fP \fB-s\fP
\[:U]berpr\[:u]ft den Datentr\[:a]ger in Laufwerk \fI/dev/hdc\fP auf Fehler.
.TP
\fBdvdisaster\fP \fB-d\fP \fI/dev/hdc\fP \fB-i\fP \fIabbild.iso\fP \fB-r\fP
Erstellt ein Abbild vom Datentr\[:a]ger in Laufwerk \fI/dev/hdc\fP als Datei \fIabbild.iso\fP.
.TP
\fBdvdisaster\fP \fB-d\fP \fI/dev/hdc\fP \fB-i\fP \fIabbild.iso\fP \fB-e\fP \fIkorr.ecc\fP \fB-r\fP \fB--adaptive-read\fP
Verwendet die angepasste Lesestrategie, um ein Abbild vom 
Datentr\[:a]ger in Laufwerk \fI/dev/hdc\fP als Datei \fIabbild.iso\fP
zu erstellen. Der Lesevorgang wird automatisch beendet
sobald gen\[:u]gend Daten eingelesen wurden, um das Abbild mit Hilfe der 
Fehlerkorrektur-Datei \fIkorr.ecc\fP wiederherzustellen:
.TP
\fBdvdisaster\fP \fB-i\fP \fIabbild.iso\fP \fB-e\fP \fIkorr.ecc\fP \fB-c\fP
Erzeugt eine Fehlerkorrektur-Datei \fIkorr.ecc\fP f\[:u]r das Abbild \fIabbild.iso\fP.
.TP
\fBdvdisaster\fp \fB-i\fP \fIabbild.iso\fP \fB-m\fIRS02\fP \fB-n\fP \fI350000\fP \fB-c\fP
Erweitert ein Abbild \fIabbild.iso\fP mit Fehlerkorrektur-Daten,
wobei das Abbild auf nicht mehr als \fI350000\fP Sektoren vergr\[:o]ssert wird.
Ohne Angabe von \fB-n\fP wird das Abbild auf die Gr\[:o]sse des 
kleinstm\[:o]glichen Datentr\[:a]gers (CD, DVD, DVD9) erweitert.
Beachten Sie das fehlende Leerzeichen zwischen \fB-m\fP und \fIRS02\fP.
.TP
\fBdvdisaster\fP \fB-i\fP \fIabbild.iso\fP \fB-e\fP \fIkorr.ecc\fP \fB-f\fP
Wiederherstellung der Abbild-Datei \fIabbild.iso\fP 
mit Hilfe der Fehlerkorrektur-Datei \fIkorr.ecc\fP.
.TP
\fBdvdisaster\fP \fB-i\fP \fIabbild.iso\fP \fB-e\fP \fIkorr.ecc\fP \fB-t\fP
\[:U]berpr\[:u]ft den Inhalt des Abbilds \fIabbild.iso\fP 
mit Hilfe der Fehlerkorrektur-Datei \fIkorr.ecc\fP auf Vollst\[:a]ndigkeit und Korrektheit.
.TP
\fBHINWEIS:\fP
Geben Sie in den obigen Beispielen  die \fB-e korr.ecc\fP-Optionen nicht an, 
wenn Sie mit erweiterten Abbildern arbeiten.

.SH OPTIONEN
Aktions-Auswahl (mindestens eine Aktion muss gew\[:a]hlt werden):
.TP
.B \-r, \-\-read
Datentr\[:a]ger-Abbild auf Festplatte einlesen. -rn-m liest einen Bereich von
Sektoren, z.B. -r100-200.
.TP
.B \-c, \-\-create
Erzeugt Fehlerkorrektur-Daten f\[:u]r das Abbild.
.TP
.B \-f, \-\-fix
Versucht das Abbild mit Hilfe der Fehlerkorrektur-Daten zu reparieren.
.TP
.B \-s, \-\-scan
Untersucht den Datentr\[:a]ger auf Lesefehler.
.TP
.B \-t, \-\-test
Pr\[:u]ft die Struktur der .iso und .ecc - Dateien.
.TP
.B \-u, \-\-unlink
L\[:o]scht .iso - Dateien nach Beenden der vorherigen Aktionen.
.PP

Laufwerks- und Dateinamen:
.TP
.B \-d, \-\-device device
Von diesem Laufwerk lesen (Standard: /dev/cdrom).
.TP
.B \-p, \-\-prefix prefix
Anfang der .iso/.ecc - Dateien (Standard: medium.* ).
.TP
.B \-i, \-\-image imagefile
Name der Abbild - Datei (Standard: medium.iso).
.TP
.B \-e, \-\-ecc eccfile
Name der Fehlerkorrektur-Datei (Standard: medium.ecc).
.PP
.B \-\-list
Zeigt verf\[:u]gbare Laufwerke unter dem ASPI-Treiber (nur f\[:u]r Windows).
.PP

Feineinstellung (Beachten Sie die Hinweise in der Dokumentation!):
.TP
.B \-j, \-\-jump n
\[:u]berspringe n Sektoren nach einem Lesefehler (Standard: 16).
.TP
.B \-n, \-\-redundancy n%
Redundanz der Fehlerkorrektur (Standard: 14.3%).
.TP
.B \-m, \-\-method n
Fehlerkorrektur-Methoden anzeigen/ausw\[:a]hlen (Standard: RS01).
.RS
M\[:o]gliche Werte sind RS01 und RS02.
.RE
.TP
.B \-v, \-\-verbose n%
mehr erl\[:a]uternde Ausgaben
.TP
.B \-\-adaptive-read
verwende optimierte Lesestrategie f\[:u]r defekte Datentr\[:a]ger.
.TP
.B \-\-auto-suffix
automatisches Anf\[:u]gen der .iso- und .ecc-Dateiendungen.
.TP
.B \-\-cache-size n
Zwischenspeicher in MB bei .ecc-Datei-Erzeugung - (Standard: 32MB).
.TP
.B \-\-dao
unterstelle DAO; Abbild am Ende nicht k\[:u]rzen.
.TP
.B \-\-fill-unreadable n
f\[:u]lle unlesbare Sektoren mit Byte n.
.TP
.B \-\-query-size n
Ermittelt die Abbildgr\[:o]sse durch das Laufwerk oder das Dateisystem auf dem Datentr\[:a]ger
(Standard: ecc)
.RS
M\[:o]gliche Werte: drive udf ecc 
.RE
.TP
.B \-\-speed-warning n
warnt bei Geschwindigkeits\[:a]nderung um mehr als n Prozent.
.TP
.B \-\-spinup-delay n
gibt dem Laufwerk n Sekunden Zeit zum Hochlaufen.
.TP
.B \-\-split-files
Abbild in mehrere Dateien <= 2GB aufteilen.
.PP

Einstellungen f\[:u]r die graphische Benutzeroberfl\[:a]che:
.TP
.B \-\-keep-style
Style-Einstellungen nicht \[:u]berschreiben.

.SH SIEHE AUCH
.B Dokumentation
DVDISASTER ist in seinem eigenen Handbuch dokumentiert, welches in
.IR %docdir%
installiert ist.

.SH AUTHOR
DVDISASTER wurde von Carsten Gnoerlich <carsten@dvdisaster.com> geschrieben.
.PP
Diese Hilfeseite wurde von Daniel Baumann <daniel.baumann@panthera-systems.net>
f\[:u]r das Debian Projekt geschrieben (kann aber auch von Anderen verwendet
werden). Sie wurde f\[:u]r Version 0.70 von Carsten Gn\[:o]rlich erweitert.
